### ISSUE TITLE
Build issue on iOS with latest Firebase pod version (7.0.0)

### ISSUE THREAD

**Issue by QuentinFarizon** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#188]
Hello @andrehtissot and thanks again (and again !) for your great work.

**Describe the bug**
Build issue on iOS with latest Firebase pod version

**To Reproduce**
Build with latest Firebase pod version (7.0.0) : https://firebase.google.com/support/release-notes/ios

App build fail due to error :
```
/Users/vagrant/git/platforms/ios/Boks preprod/Plugins/cordova-plugin-fcm-with-dependecy-updated/AppDelegate+FCMPlugin.m:146:101: error: nullability specifier 'nonnull' conflicts with existing specifier 'nullable'
- (void)messaging:(nonnull FIRMessaging *)messaging didReceiveRegistrationToken:(nonnull NSString *)deviceToken {
                                                                                                    ^
```

Here is the documented change on the release note :
FCM :
The messaging:didReceiveRegistrationToken: is able to return a null token. Updated the API parameter fcmToken to be nullable (#5339).

I'm not on the latest version of this plugin, but I think the issue is still there :  https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/src/ios/AppDelegate%2BFCMPlugin.m#L146

As there is already code to check the nullability (https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/src/ios/AppDelegate%2BFCMPlugin.m#L148), removing the annotation is probably enough !

**Environment (please complete the following information):**
 - Developer OS and version: macOS 10.14.6 (Mojave)
 - Mobile OS and version: iOS 14.0.1
 - Cordova CLI version (cordova --version): 9.0.0
 - Cordova iOS version : 5.1.1
 - Cocoapods version (pod --version): -
 - Xcode version (xcodebuild  -version): Xcode 11.1.x

**Package.json**
Please add your package.json, as to provide the dependencies version.
```
{
  (...)
  "dependencies": {
    "@ionic-native/fcm": "^5.27.0",
    "cordova-plugin-fcm-with-dependecy-updated": "^7.0.6",
   (...)
   },
  "cordova": {
      "cordova-plugin-fcm-with-dependecy-updated": {
        "ANDROID_FCM_VERSION": "19.0.0",
        "ANDROID_GRADLE_TOOLS_VERSION": "3.5.3",
        "ANDROID_GOOGLE_SERVICES_VERSION": "4.3.3",
        "ANDROID_DEFAULT_NOTIFICATION_ICON": "@drawable/ic_boks_silhouette"
      },
   }
}
```

**Comment by QuentinFarizon** [comment]
Of course, as a workaround, fixing the pod version to 6.43.0 solves the build issue

**Comment by Geschan** [comment]
I experience the same issue when using Ionic AppFlow/Fastlane builds.

**Comment by mayur-bhandari** [comment]
@QuentinFarizon ,

Which version of the cordova-plugin-fcm-with-dependency-updated should I use to solve this issue? I was using 7.3.1 but I am getting the same error.

**Comment by QuentinFarizon** [comment]
I've attempted a fix at https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/pull/190

But I think pod versions should be fixed, and changed only when tested, as are all other dependecies, locked in package-lock.json

**Comment by QuentinFarizon** [comment]
Attempting to lock Pod version also in https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/pull/191

Both approaches are non incompatible

**Comment by mayur-bhandari** [comment]
@QuentinFarizon ,

The version is 6.34.0 and not 6.43.0. What I did was I hardcoded the pod version in platforms/ios/PodFile and it solved the issue. Hope this helps someone.

**Comment by QuentinFarizon** [comment]
@mayur-bhandari Oops, indeed, fixed

**Comment by kilghard** [comment]
Thanks @QuentinFarizon & @mayur-bhandari same issue, can confirm the podfile hardcode solves it. 
pod 'Firebase/Messaging', '~> 6.34.0'

**Comment by johnparkerg** [comment]
I'm also experiencing the same issue when using Ionic AppFlow/Fastlane builds.

**Comment by johnparkerg** [comment]
@Geschan and anybody else using AppFlow, here are steps to workaround this:

1. run `ionic cordova plugin rm cordova-plugin-fcm-with-dependecy-updated`
2. fork this repository https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated
3. Make changes #191 or #190 (I did #191) to your fork
4. run `ionic cordova plugin add https://github.com/{{USERNAME}}/cordova-plugin-fcm-with-dependecy-updated.git` <-- Change url to match your repository's url

Let me know if this helped you.

**Comment by QuentinFarizon** [comment]
You can also directly use mine :

run ionic cordova plugin add  https://github.com/
<https://github.com/%7B%7BUSERNAME%7D%7D/cordova-plugin-fcm-with-dependecy-updated.git>
QuentinFarizon/cordova-plugin-fcm-with-dependecy-updated.git
<https://github.com/%7B%7BUSERNAME%7D%7D/cordova-plugin-fcm-with-dependecy-updated.git>
#fix_firebase_pod_version

Le sam. 31 oct. 2020 à 08:33, John Parker <notifications@github.com> a
écrit :

**Comment by johnparkerg** [comment]
Thanks @QuentinFarizon ! For the fix and for this.

**Comment by andrehtissot** [comment]
Hi @QuentinFarizon!

Thank you for the fix in the PR. It's been merged!

And besides that, if something like this happens again in the future, the plugin preference `IOS_FIREBASE_MESSAGING_VERSION` can be set on install.
