### ISSUE TITLE
Custom sound not working in Android

### ISSUE THREAD

**Issue by leocharrua** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#84]
Hello. Thanks for your work with this plugin.

I was working with an old version of this plugin (4.4.0) ... and with this version custom sound worked ok, following this steps: coping the sound file to platforms\android\app\src\main\res\raw and sending in the notification post: 

{
	"notification": {
		"sound": "sound_file_name_with_out_extension"

Now, I've updated to the last version of the plugin (6.4.1), and now the custom sound doesn't work anymore ... allways get the default sound.

Can you help me?

Thanks

**Comment by andrehtissot** [comment]
For newer Androids 8.0+, it is now expected to have the sound defined by channel. For older Android versions, you can still keep sending the sound in the push payload.


From the app:
```javascript
FCMPlugin.createNotificationChannelAndroid({
  id: "defaultChannel",
  name: "Default",
  importance: "high",
  sound: "customAlert",
});
```

And from the server, you add the android_channel_id, like:
```json
"notification": {
  "title": "...",
  "body": "...",
  "sound": "customAlert",
  "android_channel_id": "defaultChannel"
},
...
```

Let me know if this doesn't work for you.

**Comment by leocharrua** [comment]
Hello. Thanks for your answer!!! 

Sorry ... I'm very confuse here.

I'm only including in my code:

          import { FCM } from '@ionic-native/fcm/ngx';

how is indicated in the ionic docs and other pages with examples that includes your plugin:

https://ionicframework.com/docs/native/fcm

But now, I need to use a function (createNotificationChannelAndroid) from "FCMPlugin". What I must include now in my code to make it work? (because I get a error ... function doesn't exists in FCM).

Sorry about this newbe question, but I really confused about this.

If you have a complete example code, I'd appreciate it.

Thanks again.

**Comment by andrehtissot** [comment]
Relax, it's not really that simple anyway. The `cordova-plugin-fcm-with-dependecy-updated` plugin itself is not focused on ionic, and it it available in the JS global context as `FCMPlugin`.

What `native/fcm` package does is wrap this plugin's functions into more ionic-friendly methods and objects (Promises and Observables), which would not be natively supported on the older Android versions (API 19), which cordova supports.

The unfortunate result is that, some times, a new feature, like `createNotificationChannelAndroid` may be available to use, but won't have its proper typescript definition, as it is not included in the `native/fcm` package.

I've created a PR 8 days ago (https://github.com/ionic-team/ionic-native/pull/3430), which have still not been merged, to fix that.

I've been studying how to get these definitions as part of the main plugin.

For now, to workaround it, what you can do is to call like this:
```typescript
(window as any).createNotificationChannelAndroid({
  id: "defaultChannel",
  name: "Default",
  importance: "high",
  sound: "customAlert",
});
```

Let me know if this doesn't work for you. Or if you have any other questions.

**Comment by leocharrua** [comment]
Thanks André!!!

With this code I'm getting this error:

ERROR TypeError: window.createNotificationChannelAndroid is not a function

I forget something? I must change anything?

This code must be in any specific part of the app?

Thanks again!!!

**Comment by andrehtissot** [comment]
That was my mistake, I'm sorry. I forgot the `FCMPlugin` part.

I meant:
```typescript
(window as any).FCMPlugin.createNotificationChannelAndroid({
  id: "defaultChannel",
  name: "Default",
  importance: "high",
  sound: "customAlert",
});
```

**Comment by leocharrua** [comment]
Uf!!! Sorry ... Now I get this error:

ERROR TypeError: Cannot read property 'createNotificationChannelAndroid' of undefined

Also tried adding:

import { FCMPlugin } from 'cordova-plugin-fcm-with-dependecy-updated';

but I get the same error.

How I can access FCMPlugin from ionic? Any Import? In app.module.ts or in the page module?

Sorry and Thanks again.

**Comment by leocharrua** [comment]
Hello André!!!

Any comments?

My options? Can I downgrade to a functional version of this plugin? Which version do you recommend?

Thanks

**Comment by andrehtissot** [comment]
If it was working with v4.4.0. I'd recommend to got back to that as your work shouldn't stop for these. But soon, this definition issue will be solved.

I started preparing something else, which is not yet ready for prime time, but it's close to.

As you can see here https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/tree/moving-plugin-interface-to-ts-and-other-improvements/ionic the plugin js interface is been refactored and there will be a ionic-specific definition.

I'm still working on it. But feedback is appreciated.

**Comment by leocharrua** [comment]
Hello André!!! Thanks for your answer!!!

Thanks for all your work for the comunity ... by the way, the ion-specific definition looks great!!! 

Please, can you give me some notes about this?:

1) I thinked in update to the last version of the plugin, because I have this error en iOS with the 4.4.0 version:

/Plugins/cordova-plugin-fcm-with-dependecy-updated/AppDelegate+FCMPlugin.m: runtime: UI API called from background thread: -[UIApplication registerForRemoteNotifications] must be used from main thread only

Is there any version of the plugin that works with custom sound in Android and without this error in iOS?

2) Why you suggestion don't work for me?:

(window as any).FCMPlugin.createNotificationChannelAndroid({
  id: "defaultChannel",
  name: "Default",
  importance: "high",
  sound: "customAlert",
});

I need to do something to get it to work?

Thanks again.

**Comment by leocharrua** [comment]
Hello again André!!!

I downgraded the plugin to 4.4.0 version ... and the notification custom sound still not playing(mp3 files are in res/raw)  ... grrrr 

Also, I tested changing de Android API from 29 to 28 ... changing library @ionic-native/fcm from 5.26.0 to 5.22.0

I'm testing in two different devices of different brands.

I don't know what else ... before updating the plugin this worked ok in Android ... grrrr

Any ideas?

Thanks

**Comment by andrehtissot** [comment]
I have news. The new version `7.0.0-beta.0` is now available.
https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/tree/v7.0.0-beta

It supports ionic v4 and v5. And it brings all current features with lower overhead.

**Comment by andrehtissot** [comment]
Let me know if you have any issues. And I appreciate all the feedback you can give for this beta.

**Comment by leocharrua** [comment]
Hello André!!!

Good work!!! I will try the new version ... but I don't know how to use the new features from Ionic 5!!!
Can you give me some directions? What I need to import for use window.FCMPlugin?

Thanks again!!!

**Comment by RichardBoyder** [comment]
@leocharrua  
There is documentation at the link.
For Example:
import { FCM } from "cordova-plugin-fcm-with-dependecy-updated/ionic";

https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/tree/v7.0.0-beta

**Comment by meghanadixit1** [comment]
> lower

Hey will it not be supported on  V3 anymore?

**Comment by andrehtissot** [comment]
@meghanadixit1 Honestly I didn't think it was used anymore. If you require it @meghanadixit1, please share a "hello world" app with that version, to help me debug it and add the implementation for that versions as well.

**Comment by meghanadixit1** [comment]
> @meghanadixit1 Honestly I didn't think it was used anymore. If you require it @meghanadixit1, please share a "hello world" app with that version, to help me debug it and add the implementation for that versions as well.

@andrehtissot  We have some of the projects in v3, yet to be migrated. Will need a support in v3 too. 
Sure will send the simple helllo world app

**Comment by leocharrua** [comment]
Hello André!!!

1) I'm using:

import { FCM } from "cordova-plugin-fcm-with-dependecy-updated/ionic/ngx";

Because I come back from:

import { FCM } from '@ionic-native/fcm/ngx';

... Then I replaced one for other ... is that correct?


2) When I add the plugin:

ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated@7.0.0-beta.0

and build for android I get no errors.

But when I run the app in the android device ... I get a white screen and in the chrome console this messages:

--------

Unhandled Promise rejection: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping. ; Zone: <root> ; Task: Promise.then ; Value: Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.

:8100/polyfills.js:672 

FCMPlugin: has been created   :8100/plugins/cordova-plugin-fcm-with-dependecy-updated/www/FCMPlugin.js:21 
FCMPlugin: Ready!			  :8100/plugins/cordova-plugin-fcm-with-dependecy-updated/www/FCMPlugin.js:72 

--------											

I know this is not a error of the plugin properly ... but I get this error when I add it to the build. I don't get these errors with 4.4.0 or 6.4.0 plugin versions!!!											
I attach the package.json dependencies ... just in case.

I appreciate any help.

Thank you so much.

**Comment by andrehtissot** [comment]
@leocharrua, I've created an specific issue for this error https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/93.
